services:
  infl:
    image: influxdb
    container_name: Influxdb_con
    ports:
      - 8088:80
    volumes:
      - ./anjana:/anjana_c
    networks:
      - Anjana
networks:
  Anjana:
    driver: bridge



---
version: '3.8'
services:
  webserver:
    image: nginx
    container_name: anjana_Container
    ports:
      - "8080:80"
    networks:
      - my_network
    volumes:
      - web_data:/usr/share/nginx/html

networks:
  my_network:
    driver: bridge

volumes:
  web_data:





