# Secret Example: Stores sensitive data, here used for a DB password
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret # Name of the Secret
  namespace: nginx-namespace # Secret belongs to nginx-namespace
type: Opaque # Default secret type for arbitrary user data
data:
  DB_PASSWORD: cGFzc3dvcmQxMjM= # Base64 encoded password 'password123'
