---
- name: Clone a Git repo and execute Maven goals
  hosts: localhost
  become: yes

  vars:
    repo_url: "https://github.com/Anjanachari/Uese_Name.git"
    repo_dest: "/mnt/c/Users/anjan/OneDrive/Learning/Ansible/Anjana"
    maven_goals: "clean install"

  tasks:

  - name: Clone the Git repository
    git:
      repo: "{{ repo_url }}"
      dest: "{{ repo_dest }}"
      version: main
      force: yes

  - name: Run Maven goals
    command: mvn {{ maven_goals }}
    args:
      chdir: "{{ repo_dest }}"
