# Use the official NGINX image from Docker Hub
FROM nginx:latest

# Copy custom HTML file to replace the default NGINX page
COPY my-nginx/html/index.html /usr/share/nginx/html/index.html

# Expose port 80 for the NGINX service
EXPOSE 80
